name: Release

on:
  push:

jobs:
  release:
    name: build and release electron app

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: yarn install

      - uses: actions/checkout@v2
      - name: install rust
        uses: actions-rs/toolchain@v1
      - run: cargo check

      - run: yarn build
      - run: yarn build:napi
      - run: ls -al ./dist
