name: Release

on:
  push:

jobs:
  release:
    name: build and release electron app

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest, macos-latest-large]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: intall rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - run: cargo check

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: yarn install

      - run: yarn build:napi
      - run: yarn build
      - run: ls -al ./dist
      - run: yarn package
      - run: ls -al ./out
